import streamlit as st

LABELS = {
    "FAQ": {"English": "FAQ", "Korean": "자주 묻는 질문", "Spanish": "Preguntas frecuentes", "Japanese": "よくある質問"},
    "Q1": {
        "English": """Has Macrogen Office been officially launched?""",
        "Korean": """마크로젠 오피스는 정식으로 런칭되었나요?""",
        "Spanish": """¿Ha sido lanzado oficialmente Macrogen Office?""",
        "Japanese": """マクロジェンオフィスは正式に発売されましたか?""",
    },
    "A1": {
        "English": """The Macrogen Office is still in its beta version. Please note that the chatbot can be updated at any time without prior notice. If the chatbot exhibits any strange behavior or technical issues, please feel free to contact the Technical Strategy Office at any time. Additionally, if you have any suggestions regarding new features or UI/UX improvements, please let us know.""",
        "Korean": """마크로젠 오피스는 아직 베타버전입니다. 챗봇이 사전고지 없이 언제든지 업데이트 될 수 있으니 참고 바랍니다. 혹시나 챗봇이 이상한 행동을 보이거나 기술적 결함을 보이면 언제든지 편하게 기술전략실로 문의주시기 바랍니다. 또한 새로운 기능 혹은 UI/UX 적으로 건의사항이 있으시면 말씀 부탁드립니다.""",
        "Spanish": """La oficina de Macrogen todavía está en su versión beta. Tenga en cuenta que el chatbot puede actualizarse en cualquier momento sin previo aviso. Si el chatbot presenta algún comportamiento extraño o problemas técnicos, no dude en ponerse en contacto con la Oficina de Estrategia Técnica en cualquier momento. Además, si tiene alguna sugerencia sobre nuevas funciones o mejoras en la UI/UX, háganoslo saber.""",
        "Japanese": """マクロジェンオフィスはまだベータ版です。チャットボットは予告なしにいつでもアップデートされる可能性があるのでご注意ください。チャットボットが奇妙な動作をしたり、技術的な欠陥を見せたりした場合は、いつでも気軽に技術戦略室にお問い合わせください。また、新しい機能やUI/UXに関するご提案がありましたら、お知らせください。""",
    },
    "Q2": {
        "English": """What is the difference between OpenAI ChatGPT and Macrogen Office?""",
        "Korean": """기존 OpenAI ChatGPT 와 마크로젠 오피스의 차이가 무엇인가요?""",
        "Spanish": """¿Cuál es la diferencia entre OpenAI ChatGPT y Macrogen Office?""",
        "Japanese": """OpenAIのChatGPTとMacrogen Officeの違いは何ですか?""",
    },
    "A2": {
        "English": r"""OpenAI ChatGPT (https://chatgpt.com/) also has a free version. The problem with using the free version is that 1) access to the latest ChatGPT model, GPT-4, is restricted, and 2) user conversations are stored by OpenAI and used as training data. This means that sensitive information from our company could be indiscriminately provided to them. You should never use it this way within the company. By paying a monthly subscription fee of \$20 for ChatGPT Plus, you can use the GPT-4 model relatively freely and your data will not be used as training data (users can opt out). However, supporting all over 500 employees with a \$20 monthly fee is not realistic. Additionally, ChatGPT is designed to assist with the most general situations, providing responses based solely on pre-learned information without knowing the specific context and information of Macrogen. For example, ChatGPT does not know Macrogen's approval line for expense reports. To overcome these issues, we developed Macrogen Office. Macrogen Office uses the OpenAI API to maintain the existing ChatGPT experience, but you only pay for the amount you use the API, so no additional subscription fee is incurred. The data is also not used as training data (https://openai.com/enterprise-privacy/; “We do not train on your business data (data from ChatGPT Team, ChatGPT Enterprise, or our API Platform”). Additionally, it can be designed to respond or function based on information specific to Macrogen.""",
        "Korean": r"""OpenAI ChatGPT(https://chatgpt.com/)는 무료 버전도 있습니다. 문제는 무료버전을 사용하게 되면 1) ChatGPT 최신 모델인 GPT-4o 접근이 제한되고 2) 사용자의 대화 내용등이 OpenAI에 저장되어 그들의 trading data로 사용됩니다. 본사의 민감한 정보를 무분별하게 그들에게 제공하게 되는 것입니다. 절대로 회사 내에서 이렇게 사용하지 않으셔야겠습니다. 한달에 ChatGPT Plus 구독료 \$20 을 내면 비교적 GPT-4o 모델을 자유롭게 사용할 수 있고 또 training data 로 제공되지 않습니다(이용자가 opt out 설정 가능). 하지만 500명이 넘는 임직원들 모두 매달 \$20 지원하는건 현실적이지 않습니다. 또한 ChatGPT 는 가장 일반적인 상황에 도움이 되도록 만들어졌기 때문에 마크로젠의 상황과 정보를 모르는채 이미 학습된 정보로만 답변을 줍니다. 예시로, ChatGPT는 마크로젠의 품의 결재라인을 모릅니다. 이러한 문제점들을 넘어서고자 마크로젠 오피스를 개발하게 되었습니다. 마크로젠 오피스는 OpenAI API를 사용하여 기존의 ChatGPT 경험은 그대로 주면서 API를 사용한 만큼만 돈을 내기 때문에 따로 구독료는 발생하지 않습니다. 데이터 역시 training data로 사용되지 않습니다(https://openai.com/enterprise-privacy/; “We do not train on your business data (data from ChatGPT Team, ChatGPT Enterprise, or our API Platform”). 또한 마크로젠만을 위한 정보를 토대로 답변을 하거나 기능을 할 수 있도록 설계할 수 있습니다.""",
        "Spanish": r"""OpenAI ChatGPT (https://chatgpt.com/) también tiene una versión gratuita. El problema con el uso de la versión gratuita es que 1) el acceso al último modelo de ChatGPT, GPT-4, está restringido, y 2) las conversaciones de los usuarios se almacenan en OpenAI y se utilizan como datos de entrenamiento. Esto significa que la información sensible de nuestra empresa podría ser proporcionada indiscriminadamente a ellos. Nunca deben usarlo de esta manera dentro de la empresa. Al pagar una tarifa de suscripción mensual de \$20 por ChatGPT Plus, pueden usar el modelo GPT-4 relativamente libremente y sus datos no se utilizarán como datos de entrenamiento (los usuarios pueden optar por no participar). Sin embargo, apoyar a más de 500 empleados con una tarifa mensual de \$20 no es realista. Además, ChatGPT está diseñado para ayudar en las situaciones más generales, proporcionando respuestas basadas únicamente en información preaprendida sin conocer el contexto específico y la información de Macrogen. Por ejemplo, ChatGPT no conoce la línea de aprobación de Macrogen para informes de gastos. Para superar estos problemas, desarrollamos Macrogen Office. Macrogen Office utiliza la API de OpenAI para mantener la experiencia existente de ChatGPT, pero solo paga por la cantidad que usa la API, por lo que no se incurre en una tarifa de suscripción adicional. Los datos tampoco se utilizan como datos de entrenamiento (https://openai.com/enterprise-privacy/; “No entrenamos con sus datos comerciales (datos de ChatGPT Team, ChatGPT Enterprise o nuestra plataforma API”). Además, puede diseñarse para responder o funcionar en función de la información específica de Macrogen.""",
        "Japanese": r"""OpenAI ChatGPT (https://chatgpt.com/) には無料バージョンもあります。無料バージョンを使用する問題点は、1) 最新のChatGPTモデルであるGPT-4へのアクセスが制限されること、2) ユーザーの会話内容がOpenAIに保存され、トレーニングデータとして使用されることです。これは、当社の機密情報が無分別に提供される可能性があることを意味します。社内でこのように使用してはなりません。月額\$20のサブスクリプション料を支払うと、ChatGPT Plusを利用でき、比較的自由にGPT-4モデルを使用でき、データはトレーニングデータとして使用されません (利用者はオプトアウト設定が可能です)。しかし、500人以上の従業員全員に毎月\$20を支援するのは現実的ではありません。また、ChatGPTは最も一般的な状況に対応するよう設計されているため、マクロジェンの状況や情報を知らないまま、事前に学習された情報のみに基づいて回答を提供します。例えば、ChatGPTはマクロジェンの費用報告の承認ラインを知りません。これらの問題を克服するために、マクロジェンオフィスを開発しました。マクロジェンオフィスはOpenAI APIを使用して既存のChatGPTの体験を維持しながら、APIの使用量に応じてのみ料金を支払うため、追加のサブスクリプション料は発生しません。データもトレーニングデータとして使用されません (https://openai.com/enterprise-privacy/; “We do not train on your business data (data from ChatGPT Team, ChatGPT Enterprise, or our API Platform”)）。さらに、マクロジェン専用の情報に基づいて応答や機能を設計することができます。""",
    },
    "Q3": {
        "English": """How do I log in?""",
        "Korean": """로그인은 어떻게 하나요?""",
        "Spanish": """¿Cómo inicio sesión?""",
        "Japanese": """どうやってログインしますか?""",
    },
    "A3": {
        "English": """You can use your Daou Office accounts. For example, if your account is sbslee@macrogen.com, you can log in using sbslee@macrogen.com. The password has been initially set to '123' for all accounts. You can change the password after logging in. Once you change your password, it will be stored as a hashed value, so even the Technical Strategy Office cannot see your password. However, since this is a beta test, we recommend that you set a password specifically for Macrogen Office instead of using your usual password.""",
        "Korean": """여러분들의 다우오피스 계정을 사용하시면 됩니다. 예를들어 sbslee@macrogen.com 이 계정이시라면 sbslee@macrogen.com 를 치고 접속이 가능합니다. 비밀번호는 현재 일괄적으로 '123' 으로 설정해놓았습니다. 비밀번호는 로그인 후 변경 가능합니다. 비밀번호는 변경하시게 되면 hash 값으로 변환되어 저장되기 때문에 기술전략실에서도 사용하신 비밀번호를 알 수 없습니다. 다만, 베타 테스트이기 때문에 평소에 자주 사용하시는 비밀번호 보다는 마크로젠 오피스를 위한 비밀번호를 설정하시길 추천드립니다.""",
        "Spanish": """Pueden usar sus cuentas de Daou Office. Por ejemplo, si su cuenta es sbslee@macrogen.com, pueden iniciar sesión utilizando sbslee@macrogen.com. La contraseña se ha establecido inicialmente en '123' para todas las cuentas. Pueden cambiar la contraseña después de iniciar sesión. Una vez que cambien su contraseña, se almacenará como un valor hash, por lo que ni siquiera la Oficina de Estrategia Técnica podrá ver su contraseña. Sin embargo, dado que esta es una prueba beta, recomendamos que configuren una contraseña específicamente para Macrogen Office en lugar de usar su contraseña habitual.""",
        "Japanese": """皆様のダウオフィスアカウントをご利用いただけます。例えば、sbslee@macrogen.com があなたのアカウントであれば、sbslee@macrogen.com を入力してログインできます。初期パスワードは一括して「123」に設定されています。パスワードはログイン後に変更可能です。パスワードを変更すると、ハッシュ値として保存されるため、技術戦略室でも使用したパスワードを知ることはできません。ただし、ベータテスト中ですので、普段使用しているパスワードではなく、マクロジェンオフィス専用のパスワードを設定することをお勧めします。""",
    },
    "Q4": {
        "English": "How do I use Macrogen Office?",
        "Korean": "마크로젠 오피스는 어떻게 사용하면 되나요?",
        "Spanish": "¿Cómo uso Macrogen Office?",
        "Japanese": "Macrogen Officeをどのように使用しますか?",
    },
    "A4": {
        "English": """Like any modern tool such as smartphones, the power of AI also varies depending on the user's ability and creativity. At its most basic level, it can be used to find information, search within files, code, analyze data, generate images, and browse the internet. In short, it supports all the functions of the existing ChatGPT GPT-4 model. In the Genome Business Unit beta test, the areas where users frequently used Macrogen Office included: 1) uploading files such as experimental protocol PDFs to Macrogen Office and finding the desired information within those files, 2) uploading Excel files containing table data such as sales information to Macrogen Office, creating graphs, or changing the data format using natural language without complex Excel functions, and then downloading it, 3) requesting the creation of programs that are useful for work even without any programming experience. Macrogen Office also has functions that the existing ChatGPT cannot perform. For example, if you ask "Show me the approval line for corporate card expenses under 100,000 won," the existing ChatGPT might make up a story (i.e., hallucinate). Macrogen Office will analyze the company's approval line and provide the exact approval process. These unique functions of Macrogen will continue to be added in the future. Please let us know the functions you need, and we will support them based on development difficulty and importance.""",
        "Korean": """스마트폰 등 어떤 현대 도구와 마찬가지로, AI 역시 사용자의 능력 및 창의성에 따라 발휘할 수 있는 힘이 다릅니다. 가장 기본적으로는 정보를 찾는 용도로 사용할 수 있겠으며, 파일내 검색, 코딩도 가능하고, 데이터 분석, 이미지 생성, 인터넷 브라우징 기능도 있습니다. 한마디로 기존의 ChatGPT GPT-4o 모델이 지원하는 기능은 모두 지원합니다. 지놈사업본부 베타 테스트에서 이용자분들께서 많이 사용하신 업무 영역은 1) 실험 프로토콜 PDF와 같은 파일을 마크로젠 오피스에 업로드하고 해당 파일에서 원하는 정보 찾기, 2) 매출 정보와 같은 테이블 데이터가 담긴 엑셀 파일을 마크로젠 오피스에 업로드하고 그래프를 그리거나 복잡한 엑셀 함수를 사용하지 않고 자연어로만 데이터 형식 바꾼 뒤 다운로드 하기, 3) 프로그래밍 경험이 전혀 없어도 실무에 도움이 되는 프로그램 만들어달라고 요청하기 등이 있었습니다. 마크로젠 오피스는 기존의 ChatGPT 가 하지 못하는 기능들도 있습니다. 예를들어, "비용집행 법인카드 10만원이하 결재라인 알려줘" 라고 던지면 기존 ChatGPT 는 이야기를 지어내서 답변할 것입니다 (i.e., 할루시네이션). 마크로젠 오피스는 본사의 결재라인을 분석하여 정확한 결재라인을 돌려줄 것입니다. 이런 마크로젠만의 기능들은 추후에 계속해서 추가 될 예정입니다. 필요하신 기능들을 알려주시면 개발 난이도 및 중요성에 따라 지원하도록 하겠습니다.""",
        "Spanish": """Al igual que cualquier herramienta moderna como los teléfonos inteligentes, el poder de la IA también varía según la habilidad y creatividad del usuario. A su nivel más básico, se puede usar para encontrar información, buscar dentro de archivos, programar, analizar datos, generar imágenes y navegar por internet. En resumen, admite todas las funciones del modelo ChatGPT GPT-4 existente. En la prueba beta de la Unidad de Negocios de Genomas, las áreas en las que los usuarios utilizaron frecuentemente Macrogen Office incluyeron: 1) cargar archivos como protocolos experimentales en PDF en Macrogen Office y encontrar la información deseada dentro de esos archivos, 2) cargar archivos de Excel que contienen datos tabulares como información de ventas en Macrogen Office, crear gráficos o cambiar el formato de los datos usando lenguaje natural sin funciones complejas de Excel, y luego descargarlos, 3) solicitar la creación de programas útiles para el trabajo incluso sin ninguna experiencia en programación. Macrogen Office también tiene funciones que el ChatGPT existente no puede realizar. Por ejemplo, si preguntas "Muéstrame la línea de aprobación para gastos con tarjeta corporativa menores de 100,000 wones," el ChatGPT existente podría inventar una historia (es decir, alucinar). Macrogen Office analizará la línea de aprobación de la empresa y proporcionará el proceso de aprobación exacto. Estas funciones únicas de Macrogen continuarán añadiéndose en el futuro. Háganos saber las funciones que necesita, y las apoyaremos según la dificultad de desarrollo e importancia.""",
        "Japanese": """スマートフォンなどの現代のツールと同様に、AIの力もユーザーの能力や創造性に応じて異なります。最も基本的には、情報を検索する用途として使用でき、ファイル内検索、コーディング、データ分析、画像生成、インターネット閲覧機能もあります。つまり、既存のChatGPT GPT-4モデルがサポートするすべての機能をサポートします。ゲノム事業本部のベータテストで、ユーザーが多く使用した業務領域は次のとおりです。1) 実験プロトコルPDFなどのファイルをマクロジェンオフィスにアップロードし、そのファイルから必要な情報を見つける、2) 売上情報などの表データを含むExcelファイルをマクロジェンオフィスにアップロードし、グラフを作成したり、複雑なExcel関数を使用せずに自然言語でデータ形式を変更したりしてダウンロードする、3) プログラミングの経験が全くなくても実務に役立つプログラムを作成するように依頼するなどがありました。マクロジェンオフィスには、既存のChatGPTではできない機能もあります。たとえば、「費用執行法人カード10万円以下の承認ラインを教えて」と尋ねると、既存のChatGPTは物語を作り上げて答えるでしょう (つまり、幻覚を起こす)。マクロジェンオフィスは、会社の承認ラインを分析し、正確な承認ラインを返します。このようなマクロジェン独自の機能は今後も追加される予定です。必要な機能をお知らせいただければ、開発の難易度と重要性に応じてサポートいたします。""",
    },
    "Q5": {
        "English": """What are the future plans?""",
        "Korean": """앞으로의 계획이 무엇인가요?""",
        "Spanish": """¿Cuáles son los planes futuros?""",
        "Japanese": """今後の計画は何ですか?""",
    },
    "A5": {
        "English": """Since it is still in beta, we are focusing on stabilization. Although the conversation saving feature is supported, files are not stored, and we plan to identify and develop improvements in these areas. Additionally, while Macrogen Office is used in a chatbot form, it can also be utilized from an automation perspective using the ChatGPT API, not just in chatbot form. For example, in the NGS Data Analysis Department, there are often situations where re-demultiplexing is needed after demultiplexing at the end of an NGS experiment. We are testing whether it is possible to develop a pipeline based on the ChatGPT API that allows AI to review the given LIMS data and determine the need for re-demultiplexing for each sample, without the researcher having to investigate the issue directly. Therefore, even if it is not in chatbot form, we can review whether ChatGPT can replace repetitive tasks that require human judgment from an automation perspective. Please contact us if needed. Another example is if you receive documents in a specific format from customers and manually type them to digitize the content; we can explore automating such processes as well.""",
        "Korean": """아직까지 베타 버전이기 때문에 안정화에 집중하고 있습니다. 또한 대화 저장하기 기능이 지원은 되지만 파일들은 저장되지 않기 때문에, 이런 부분들에 있어 개선사항을 발굴하여 개발할 예정입니다. 그리고 마크로젠 오피스는 챗봇 형태로 사용하고 있지만 ChatGPT API 를 사용하면 꼭 챗봇 형태가 아닌 자동화 관점에서도 사용될 수 있습니다. 예를들어 현재 NGS데이터분석부문에서는 NGS 실험이 끝난 후 demultiplexing 했을때 re-demultiplexing 을 해야하는 상황이 자주 발생하는데, 이때 연구자가 직접 문제를 조사하지 않고 AI 가 주어진 LIMS 데이터를 보고 판단하여 각 샘플별 re-demultiplexing 여부를 결정하는 파이프라인을 ChatGPT API 기반하여 개발 가능한지 여부 테스트 중입니다. 따라서, 꼭 챗봇 형태가 아니더라도 자동화 관점에서 사람이 반복적으로 무엇인가를 보고 판단해야하는 작업을 ChatGPT 가 대체해줄 수 있는지 여부를 검토해드릴 수 있으니 필요하시면 연락 주시기 바랍니다. 다른 예시는, 특정 포맷의 서류를 고객으로부터 수기로 작성하여 받은 다음 해당 내용을 일일이 디지털화 하려고 타이핑을 하고 있으시다면 그런 부분도 자동화 해볼 수 있습니다.""",
        "Spanish": """Como todavía está en beta, nos estamos enfocando en la estabilización. Aunque la función de guardar conversaciones está soportada, los archivos no se almacenan, y planeamos identificar y desarrollar mejoras en estas áreas. Además, aunque Macrogen Office se utiliza en forma de chatbot, también puede utilizarse desde una perspectiva de automatización usando la API de ChatGPT, no solo en forma de chatbot. Por ejemplo, en el Departamento de Análisis de Datos NGS, a menudo hay situaciones en las que se necesita re-demultiplexing después de demultiplexing al final de un experimento NGS. Estamos probando si es posible desarrollar un pipeline basado en la API de ChatGPT que permita a la IA revisar los datos de LIMS proporcionados y determinar la necesidad de re-demultiplexing para cada muestra, sin que el investigador tenga que investigar el problema directamente. Por lo tanto, incluso si no es en forma de chatbot, podemos revisar si ChatGPT puede reemplazar tareas repetitivas que requieren juicio humano desde una perspectiva de automatización. Por favor, contáctenos si es necesario. Otro ejemplo es si reciben documentos en un formato específico de los clientes y los escriben manualmente para digitalizar el contenido; también podemos explorar la automatización de estos procesos.""",
        "Japanese": """まだベータ版のため、安定化に注力しています。会話保存機能はサポートされていますが、ファイルは保存されないため、この部分の改善点を発掘して開発する予定です。また、マクロジェンオフィスはチャットボットの形で使用されていますが、ChatGPT APIを使用すれば、必ずしもチャットボット形式に限らず、オートメーションの観点からも使用できます。例えば、NGSデータ解析部門では、NGS実験終了後にデムルチプレクシングを行った後で再デムルチプレクシングが必要になる状況がよく発生しますが、このとき研究者が直接問題を調査せずに、AIが与えられたLIMSデータを見て各サンプルごとの再デムルチプレクシングの必要性を判断するパイプラインをChatGPT APIを基に開発できるかどうかをテスト中です。したがって、必ずしもチャットボット形式でなくても、自動化の観点から人間が繰り返し何かを見て判断しなければならない作業をChatGPTが代替できるかどうかを検討することができますので、必要があればご連絡ください。もう一つの例として、特定のフォーマットの書類を顧客から手書きで受け取り、その内容を一つ一つデジタル化するためにタイピングしている場合、その部分も自動化を検討できます。""",
    }
}

def main():
    st.header(LABELS["FAQ"][st.session_state.language])

    with st.expander(LABELS["Q1"][st.session_state.language]):
        st.write(LABELS["A1"][st.session_state.language])
    with st.expander(LABELS["Q2"][st.session_state.language]):
        st.write(LABELS["A2"][st.session_state.language])
    with st.expander(LABELS["Q3"][st.session_state.language]):
        st.write(LABELS["A3"][st.session_state.language])
    with st.expander(LABELS["Q4"][st.session_state.language]):
        st.write(LABELS["A4"][st.session_state.language])
    with st.expander(LABELS["Q5"][st.session_state.language]):
        st.write(LABELS["A5"][st.session_state.language])

if __name__ == "__main__":
    main()
